baseURL = 'https://hakki.app/cv'
languageCode = 'en-us'
title = 'CV | HakkÄ± Cengiz'
disableKinds = ["taxonomy", "term"]

defaultContentLanguage = 'en'
[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    [languages.en.params]
      datasource = 'content.en'
  [languages.tr]
    languageName = "Turkish"
    weight = 2
    [languages.tr.params]
      datasource = 'content.tr'